spring:
  http:
    encoding:
      enabled: true
    multipart:
          max-file-size: 100MB
          max-request-size: 100MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.226.98
    port: 6379
  mail:
    host: smtp.qq.com
    username: 361059351@qq.com
    password: eikkeyqnukpebjhi
    default-encoding: UTF-8
mybatis:
  mapper-locations: classpath:com/lkhu/springboot/mapper/*.xml
  configuration:
    call-setters-on-nulls: true
server:
  compression:
    enabled: true
mail:
  fromMail:
    addr: 361059351@qq.com



